export const siteConfig = {
  name: "Highly Editive",
  title: "Highly Editive",
  description:
    "Professional video editing services for creators, agencies, and brands.",
  url: "https://highlyeditive.com",
  ogImage: "/og/default.png",
  logo: "",
  email: "highlyeditive@gmail.com",
  locale: "en_US",
  language: "en",
  creator: "Highly Editive",
  publisher: "Highly Editive",
  keywords: [
    "video editing",
    "professional video editor",
    "content editing services",
    "youtube video editing",
    "reels editing",
    "Cinematic Edits",
    "Event Recaps",
    "Commercials",
    "Brand Video",
    "Talking Head",
    "Podcast Snippets",
    "Real Estate Videos",
    "Trailers",
    "Explainer Videos",
    "Instagram Reels",
    "YouTube Shorts",
    "TikTok Videos",
    "LinkedIn Posts",
    "Product Demos",
    "Testimonials",
    "Podcast Clips",
    "Tutorials",
    "Ad Creatives",
    "Behind-The-Scenes",
    "Course Content",
    "Webinar Clips",
    "Event Recaps",
  ],
};
